### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jen20** [joyent/gosign#4]
The license for this is currently GPLv3 - would you consider changing to a more permissive license such as MPL in order that other projects can use it?

**Comment by jen20** [comment]
(Some precedent for this: https://github.com/joyent/gosdc/issues/11)

**Comment by misterbisson** [comment]
Thanks for pointing this out @jen20. Fix is PR'd in https://github.com/joyent/gosign/pull/5.

**Comment by misterbisson** [comment]
I pinged a few people and heard no objections, so I merged https://github.com/joyent/gosign/pull/5.
